# ========================
# SMTP SERVER
# ========================
smtp_server: "smtp.gmail.com"
smtp_gmail_user_name: "support@voroninstudio.eu"
smtp_gmail_domain: "voroninstudio.eu"
smtp_gmail_password: "VS-support#201604"

# ========================
# HOST
# ========================
development.host: "localhost:3000"
development.host_with_port: "http://localhost:3000"

# ========================
# TINYPNG
# ========================
tinypng_key: "JFFZudld0q3AJkZogWZmy5d0wl-1My53"

# ========================
# DATABASE
# ========================
default_adapter: "*postgres"
database: "r4m_development"
postgres_user: "postgres"
postgres_password: "postgres"
# ========================
# DEVISE
# ========================
devise_secret_key: '96be7153c9de8c94b0220812b4cb5b46aa823fa37548f23f27b9eef262dd7ae0db69344675ea87e1df2279dfea1c77a4b6818635d159bed5ec308f9668f081e4'

# ========================
# SECRET_KEY
# ========================

# ========================
# GOOGLE MAPS
# ========================
GOOGLE_MAPS_API_KEY: "AIzaSyAvkI36T-T6xJe8Qif7QkbQ1xvTl8Ha_9o"
file_editor_base_dir: "config"


# ========================
# Instagram API
# ========================
instagram.client_id: "af9cce9d9c294c03a85576505129bf31"
instagram.client_secret: "71e3265f69f14b87b72bf134de59805a"
instagram.access_token: "5540814960.d90570a.8f9c72cc8f214898a6481ee2548cc1ce"